/**
 * Backend API contract types.
 *
 * These mirror the documented REST contract owned by the backend team.
 * The frontend NEVER computes these values — it only renders them.
 * If a field shape is ambiguous it is marked with `// TODO(contract)`.
 */

export type StockStatus = "healthy" | "low_stock" | "out_of_stock" | "expiring";
export type Language = "ta" | "en";

export interface ApiError {
  message: string;
  code?: string;
  details?: unknown;
}

/* ---------- auth ---------- */

export interface LoginRequest {
  email: string;
  password: string;
}

export interface SignupRequest extends LoginRequest {
  name: string;
  storeName: string;
}

export interface AuthUser {
  id: string;
  name: string;
  email: string;
  role: string;
  storeName: string;
  preferredLanguage: Language;
}

export interface LoginResponse {
  token: string;
  user: AuthUser;
}

/* ---------- dashboard ---------- */

export interface MetricValue {
  /** Pre-formatted-by-backend numeric value. */
  value: number;
  /** e.g. "INR", "units", "products" */
  unit?: string;
  /** Source/date-range context the UI must always show next to the number. */
  context: string;
  changePercent?: number | null;
}

export interface NamedMetric {
  productId?: string;
  name: string;
  value: number;
  unit?: string;
  context: string;
}

export interface ActionableInsight {
  id: string;
  /** Natural-language string generated by the backend. Rendered as-is. */
  message: string;
  severity: "info" | "warning" | "critical";
  /** Deep link target, e.g. "/inventory?filter=low-stock" */
  link?: string;
  /** Marks AI-derived recommendations (shown with an "estimate" tag). */
  isEstimate?: boolean;
}

export interface DashboardSummary {
  generatedAt: string;
  currency: string;
  todaySales: MetricValue;
  weeklySales: MetricValue;
  monthlySales: MetricValue;
  totalRevenue: MetricValue;
  totalProducts: MetricValue;
  totalUnitsSold: MetricValue;
  inventoryValue: MetricValue;
  lowStockCount: MetricValue;
  outOfStockCount: MetricValue;
  expiringCount: MetricValue;
  bestSellingProduct: NamedMetric;
  slowMovingProduct: NamedMetric;
  insights: ActionableInsight[];
}

/* ---------- products / inventory ---------- */

export interface Product {
  id: string;
  sku: string;
  name: string;
  nameTa?: string;
  category: string;
  brand: string;
  supplierId: string;
  supplierName: string;
  unit: string;
  currentStock: number;
  reorderLevel: number;
  unitCost: number;
  sellingPrice: number;
  stockValue: number;
  /** Authoritative status from the backend. Never recomputed client-side. */
  stockStatus: StockStatus;
  expiryDate?: string | null;
  updatedAt: string;
}

export interface Paginated<T> {
  data: T[];
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

export interface ProductQuery {
  search?: string;
  category?: string;
  brand?: string;
  supplierId?: string;
  stockStatus?: StockStatus | "all";
  expiringWithinDays?: number;
  sortBy?: string;
  sortDir?: "asc" | "desc";
  page?: number;
  pageSize?: number;
}

export interface TrendPoint {
  label: string;
  value: number;
  secondaryValue?: number;
}

export interface MovementEntry {
  id: string;
  date: string;
  type: "purchase" | "sale" | "adjustment" | "return";
  quantity: number;
  note?: string | undefined;
}

export interface PurchaseEntry {
  id: string;
  date: string;
  supplierName: string;
  quantity: number;
  unitCost: number;
  totalCost: number;
}

export interface ProductDetail {
  product: Product;
  salesTrend: { context: string; points: TrendPoint[] };
  purchaseHistory: PurchaseEntry[];
  movements: MovementEntry[];
  aiInsights: ActionableInsight[];
}

/* ---------- sales ---------- */

export type SalesRange = "daily" | "weekly" | "monthly";
export type SalesGroupBy = "product" | "category" | "brand";

export interface SalesQuery {
  range?: SalesRange;
  groupBy?: SalesGroupBy;
  from?: string;
  to?: string;
}

export interface SalesBreakdownRow {
  key: string;
  label: string;
  unitsSold: number;
  revenue: number;
  sharePercent: number;
}

export interface SalesOverview {
  context: string;
  currency: string;
  totalRevenue: MetricValue;
  unitsSold: MetricValue;
  transactions: MetricValue;
  averageBasket: MetricValue;
  trend: { context: string; points: TrendPoint[] };
  breakdown: SalesBreakdownRow[];
  topSellers: NamedMetric[];
  slowMovers: NamedMetric[];
}

/* ---------- suppliers ---------- */

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  phone: string;
  email: string;
  productCount: number;
  totalPurchaseValue: number;
  lastPurchaseDate: string | null;
}

export interface SupplierDetail {
  supplier: Supplier;
  products: Product[];
  purchaseHistory: PurchaseEntry[];
}

/* ---------- import ---------- */

export interface ImportColumnMapping {
  sourceColumn: string;
  targetField: string | null;
  ambiguous: boolean;
  options?: string[];
}

export interface ImportInvalidRow {
  rowNumber: number;
  reason: string;
  values: Record<string, string>;
}

export interface ImportUploadResponse {
  importId: string;
  fileName: string;
  totalRows: number;
  validRows: number;
  invalidRows: number;
  columnMappings: ImportColumnMapping[];
  invalidRowDetails: ImportInvalidRow[];
  preview: Record<string, string>[];
}

export interface ImportConfirmResponse {
  importId: string;
  status: "completed" | "partial" | "failed";
  inserted: number;
  updated: number;
  skipped: number;
  message: string;
}

export interface ImportHistoryEntry {
  importId: string;
  fileName: string;
  uploadedAt: string;
  status: "completed" | "partial" | "failed" | "pending";
  totalRows: number;
  validRows: number;
  invalidRows: number;
}

/* ---------- AI chat / voice ---------- */

export interface DataReferenceTable {
  columns: string[];
  rows: (string | number)[][];
}

export interface DataReference {
  /** Which backend tool/dataset grounded the answer. */
  source: string;
  context: string;
  table?: DataReferenceTable;
  values?: { label: string; value: string }[];
}

export interface ClarificationOption {
  label: string;
  value: string;
}

export interface AiAnswer {
  conversationId: string;
  messageId: string;
  /** Natural-language answer in the language the backend chose. Rendered as-is. */
  answer: string;
  language: Language;
  status: "answered" | "insufficient_data" | "needs_clarification";
  isEstimate?: boolean;
  dataReferences?: DataReference[];
  clarificationOptions?: ClarificationOption[];
}

export interface AiQueryRequest {
  question: string;
  language: Language;
  conversationId?: string;
}

export interface VoiceQueryResponse extends AiAnswer {
  transcript: string;
  detectedLanguage: Language;
  /** Backend-generated TTS audio URL, if any. */
  audioUrl?: string | null;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  language?: Language;
  createdAt: string;
  status?: AiAnswer["status"];
  isEstimate?: boolean;
  dataReferences?: DataReference[];
  clarificationOptions?: ClarificationOption[];
}

export interface Conversation {
  conversationId: string;
  messages: ChatMessage[];
}

/* ---------- reports ---------- */

export type ReportType =
  | "sales"
  | "inventory"
  | "low-stock"
  | "reorder"
  | "expiry"
  | "product-performance"
  | "category-performance"
  | "supplier-performance";

export interface ReportDefinition {
  type: ReportType;
  title: string;
  description: string;
  formats: ("pdf" | "excel" | "csv")[];
}

export interface ReportPreview {
  type: ReportType;
  title: string;
  context: string;
  columns: string[];
  rows: (string | number)[][];
  downloadUrl: string;
}
